# Etapa 1: Construcción de la aplicación Angular
FROM node:18-alpine AS build

WORKDIR /app

# Copiar los archivos del proyecto
COPY package*.json ./
RUN npm install

COPY . .

# Compilar la app Angular para producción
RUN npm run build

# Etapa 2: Servir la app usando Nginx
FROM nginx:alpine

# Copiar el build generado al directorio de Nginx
COPY --from=build /app/dist/AngularApp /usr/share/nginx/html

# Copiar configuración personalizada de Nginx si tienes una
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
